# -*- coding: utf-8 -*-
"""links.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCuYjk4lw9MYNs0LoAlfT6tm6jVblb8F
"""

import csv
import random
import string

# Number of URLs to generate
NUM_URLS = 100

# Sample domain extensions
tlds = [".com", ".org", ".net", ".io", ".co", ".info"]

def random_domain(length=8):
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))

# Generate URLs
urls = []
for _ in range(NUM_URLS):
    domain = random_domain(random.randint(5, 12))
    tld = random.choice(tlds)
    path = ''.join(random.choices(string.ascii_lowercase + string.digits, k=random.randint(3, 10)))
    url = f"https://www.{domain}{tld}/{path}"
    urls.append(url)

# Save to CSV
with open("random_urls.csv", "w", newline="", encoding="utf-8") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["URL"])  # Header
    for url in urls:
        writer.writerow([url])

print(f"Generated {NUM_URLS} random URLs and saved them to random_urls.csv")